source 'https://github.com/CocoaPods/Specs.git'

target 'PXInsetTextField', :exclusive => true do
  pod "PXInsetTextField", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXInsetTextField", :path => "../"

  
end
